name: Update PR Body
on:
  pull_request:
    types:
      - opened

jobs:
  update_pr_body:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Issue Number
        id: extract-issue-number
        run: echo "::set-output name=issue_number::${{ github.head_ref.match('#[0-9]+')[0] }}"

      - name: Update PR Body
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = '${{ steps.extract-issue-number.outputs.issue_number }}';
            const prBody = `${context.payload.pull_request.body}\n\nRelated issue: [${issueNumber}](https://github.com/${context.repo.owner}/${context.repo.repo}/issues/${issueNumber})`;
            await github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: prBody
            });
