name: Update PR Body
on:
  pull_request:
    types:
      - opened

jobs:
  update_pr_body:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Issue Number
        id: extract-issue-number
        run: |
          branch_name="${{ github.head_ref }}"
          issue_number=$(echo "$branch_name" | grep -oE '[0-9]+')
          echo "::set-output name=issue_number::$issue_number"

      - name: Update PR Body
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = '${{ steps.extract-issue-number.outputs.issue_number }}';
            const prBody = `${{ github.event.pull_request.body }}\n\nRelated issue: [${issueNumber}](https://github.com/${{ github.repository_owner }}/${{ github.repository }}/issues/${issueNumber})`;
            await github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: prBody
            });
